import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { UIDProvider } from "@/component/Rysa/context/UIDProvider";
import { OnSearchProvider } from "@/component/Rysa/ONDC/context/OnSearchProvider";
import { SelectedLenderProvider } from "@/component/Rysa/ONDC/context/SelectedLenderProvider";
import { OnStatusProvider } from "@/component/Rysa/ONDC/context/OnStatusProvider";
import { FinalLoanOfferProvider } from "@/component/Rysa/ONDC/context/FinalLoanOfferProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UIDProvider>
          <OnSearchProvider>
            <SelectedLenderProvider>
              <OnStatusProvider>
                <FinalLoanOfferProvider>
                  {children}
                </FinalLoanOfferProvider>
              </OnStatusProvider>
            </SelectedLenderProvider>
          </OnSearchProvider>
        </UIDProvider>
      </body>
    </html>
  );
}
